In [1]:
'''
Starting AdaBoost algrithm
'''


'\nStarting AdaBoost algrithm\n'

In [3]:
'''
IMPORTS
'''
import numpy as np
import skimage.io as io
import matplotlib.pyplot as plt
from skimage.color import rgb2gray
from skimage.morphology import binary_erosion, binary_dilation, binary_closing,skeletonize, thin
from skimage.measure import find_contours
from skimage.draw import rectangle

In [57]:
'''
Integral Image:
Input: an image I of size N x M
Output:its Integral Image II of the same size
'''

def integralImage (image):
    image = rgb2gray(image)
    n,m = image.shape
    II = np.zeros((n,m))
    for i in range(0,n):
        for j in range(0,m):
            II[i,j] = sum(sum(image[0:i+1,0:j+1]))
    return II

#arr to be a test image to test the integral function
testarr = np.array([
    [3,5,0,9],
    [3,1,4,7],
    [8,11,6,2],
    [3,14,12,25]
])

integralImg = integralImage(testarr)
print(integralImg)

[[  3.   8.   8.  17.]
 [  6.  12.  16.  32.]
 [ 14.  31.  41.  59.]
 [ 17.  48.  70. 113.]]


In [56]:
'''
Feature Scaling: The funtion scales the Feature upon a certain square of the image
    and eturns its value, to be later used in classification, to decide/compute the weight of that feature
Input: an eXe image, a Haar-like feature, its type and its parameters (i,j,w,h)
Output: the feature value
'''

#TODO for Muhammed because he's more familiar with the sizes of Haar Features
def featureScaling(partOfImage, typeOfFeature):
    if typeOfFeature == 'a':
        return 0
    elif typeOfFeature == 'b':
        return 0
    elif typeOfFeature == 'c':
        return 0
    elif typeOfFeature == 'd':
        return 0
    elif typeOfFeature == 'e':
        return 0
    else:
        print("Error: in typing the Harr type")
    

In [54]:
'''
using sum function for the integral image
'''
#sum function return the sum of 1D array for example
arr1 = [1,2,3,4]
print('sum = ',sum(arr1))

#if the function is 2D it would return the sum of each column in 1D array for example
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print('sum2 = ', sum(arr2))

#so if we want for example the summation of the a small portion of the arr2 matrix for example
'''
[1,2]
[5,6]
'''
#we would sum the summation of the 1D array i.e. sum(sum(arr2[0:2,0:2]))

print('sum3 = ', sum(sum(arr2[0:2,0:2])))

# sum(sum(arr2[0:2,0:2])) i.e. sum([6,8]) = 14


sum =  10
sum2 =  [ 6  8 10 12]
sum3 =  14
